// An array of 100 quote objects. Quotes will fetched from here incase the API fail or user is offline
const quotes = [
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { quote: "So many books, so little time.", author: "Frank Zappa" },
    { quote: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
    { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
    { quote: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
    { quote: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
    { quote: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
    { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { quote: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
    { quote: "Never bend your head. Always hold it high. Look the world straight in the eye.", author: "Helen Keller" },
    { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { quote: "Get busy living or get busy dying.", author: "Stephen King" },
    { quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "May you live every day of your life.", author: "Jonathan Swift" },
    { quote: "Life itself is the most wonderful fairy tale.", author: "Hans Christian Andersen" },
    { quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { quote: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
    { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { quote: "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", author: "Marilyn Monroe" },
    { quote: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
    { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { quote: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
    { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { quote: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
    { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { quote: "Life isn’t about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
    { quote: "There is only one happiness in this life, to love and be loved.", author: "George Sand" },
    { quote: "Let us always meet each other with smile, for the smile is the beginning of love.", author: "Mother Teresa" },
    { quote: "To love and be loved is to feel the sun from both sides.", author: "David Viscott" },
    { quote: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
    { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { quote: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
    { quote: "The mind is everything. What you think you become.", author: "Buddha" },
    { quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { quote: "Limit your “always” and your “nevers.”", author: "Amy Poehler" },
    { quote: "Nothing is impossible. The word itself says 'I’m possible!'", author: "Audrey Hepburn" },
    { quote: "You become what you believe.", author: "Oprah Winfrey" },
    { quote: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
    { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { quote: "We can do anything we want to if we stick to it long enough.", author: "Helen Keller" },
    { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { quote: "If opportunity doesn’t knock, build a door.", author: "Milton Berle" },
    { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
    { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
    { quote: "The harder I work, the luckier I get.", author: "Gary Player" },
    { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { quote: "Work hard in silence, let your success be your noise.", author: "Frank Ocean" },
    { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { quote: "If you’re going through hell, keep going.", author: "Winston Churchill" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { quote: "Opportunities multiply as they are seized.", author: "Sun Tzu" },
    { quote: "A goal is a dream with a deadline.", author: "Napoleon Hill" },
    { quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "Quality is not an act, it is a habit.", author: "Aristotle" },
    { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
    { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { quote: "Big jobs usually go to the men who prove their ability to outgrow small ones.", author: "Ralph Waldo Emerson" },
    { quote: "Keep going. Everything you need will come to you at the perfect time.", author: "Unknown" },
    { quote: "Failure is the condiment that gives success its flavor.", author: "Truman Capote" },
    { quote: "You don’t need to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
    { quote: "Stay away from those people who try to disparage your ambitions.", author: "Mark Twain" },
    { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    { quote: "If you can’t fly then run, if you can’t run then walk...", author: "Martin Luther King Jr." },
    { quote: "Only I can change my life. No one can do it for me.", author: "Carol Burnett" },
    { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { quote: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { quote: "The best dreams happen when you’re awake.", author: "Cherie Gilderbloom" },
    { quote: "What we think, we become.", author: "Buddha" },
    { quote: "Turn your can'ts into cans and your dreams into plans.", author: "Unknown" },
    { quote: "The best way out is always through.", author: "Robert Frost" }
  ];


  // 1. on loading, set quote from local array
  // 2. click on new btn
    // if user is online
        // true: try fetching quote from API
          // check if API limit is over by evaluating returned qoute and author
            // true: set quote from local array
            // false: set quote returned by API
          // catch: when error, set quote from local array
        // false: set quote from local array
  // click on twitter btn
    // if user is online
      // true: redirect to twitter post page with current quote and author
      // false: window alert "You're offline"